// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
import type React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title:
    "Deerfield & Symmes Township OH - Local Business Directory & Community Portal | MasonOne.US",
  description:
    "Explore Deerfield Township OH and Symmes Township OH local businesses, real estate listings, job opportunities, and community services through MasonOne.US portal.",
  keywords: [
    "Deerfield Township OH",
    "Symmes Township OH",
    "Township ohio",
    "Township OH Business Directory",
    "Township ohio local business",
    "Mason OH Townships",
  ],
  openGraph: {
    title: "Deerfield & Symmes Township OH Community Portal | MasonOne.US",
    description:
      "Your comprehensive resource for Deerfield and Symmes Township Ohio businesses, real estate, jobs, and community information.",
    url: "https://masonone.us/townships",
  },
  alternates: {
    canonical: "https://masonone.us/townships",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="canonical" href="https://masonone.us" />
        <meta name="geo.region" content="US-OH" />
        <meta name="geo.placename" content="Township, Ohio" />
        <meta name="geo.position" content="39.3995;-84.5613" />
        <meta name="ICBM" content="39.3995, -84.5613" />
        <meta name="theme-color" content="#4A90E2" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
